### ISSUE TITLE
Section View Expand by Default

### ISSUE THREAD

**Issue by nivritgupta** [AleSpero/ExpandableCardView#10]
is there a mechanism to Expand some section by default  , please check the screenshot . 

![skitch](https://user-images.githubusercontent.com/1904874/41900963-79b6713a-794d-11e8-8ca6-a216409c36fd.png)

**Comment by AleSpero** [comment]
Hello nivritgupta!
Is this a screenshot from your app? seems neat! 
There's no parameter to set in which the card expands itself by default, i have thought about it but i'm not sure it would be useful for most people. I will think about adding this.

In the mean time, you could just set an animation time to 0 to the card and then expanding it at the instantiation of your activity/fragment. 

Something like
```    java
    mycard.setAnimDuration(0);
    mycard.expand();
    mycard.setAnimDuration(ExpandableCardView.DEFAULT_ANIM_DURATION) //Or your custom animation time
```
If you want me to add your app in the "apps that use this library" section, just tell me and i'll do it.

Cheers!
Alessandro

**Comment by nivritgupta** [comment]
HI @AleSpero  

Thanks for your message , this screenshot is from my iOS app and my requirement is to open 4 to 5 cards by default but in your library there is no such functionality to expand the card by default   and in  order to achieve the feature I manually create my own control , but if you add the same feature in your library then it will help number of others  developers,   your library is easy to implement and  cards UI is also much better . 


Regards
niv

**Comment by AleSpero** [comment]
Hello niv, thank you for your kind words.
I will add the feature today and tomorrow.

Regards

Alessandro

Il mar 3 lug 2018, 21:07 Swift & Objective-C Developer <
notifications@github.com> ha scritto:

**Comment by nivritgupta** [comment]
@AleSpero  did you add this feature in your library .

**Comment by AleSpero** [comment]
Hello niv, 
I have just uploaded the 0.8 version with the new startExpand attribute, it will be available to get from gradle in the next hours i think.

Regards

Alessandro
