### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by lucazin** [AleSpero/ExpandableCardView#14]
Just say thanks for this lib.
Help me a lot in my project.

keep going!

**Comment by AleSpero** [comment]
Hello lucazin,

Thank you so much for your kind words. 
It means a lot to me! :)

If you want your project to be featured on the readme of this library just tell me and i'll be happy to do it.

Best of luck for your project!

Alessandro

**Comment by lucazin** [comment]
Hello AleSpero 

my project is breaking because not found 0.8 em repo.

can you help me?
