### ISSUE TITLE
How to change the title of ExpandableCardView

### ISSUE THREAD

**Issue by JianHaoZhangHB** [AleSpero/ExpandableCardView#2]
I want to use Expanable in RecyclerView.
But i dont konw how to setting the title of ExpandableCardView.
Is there any way to set the title?

**Comment by AleSpero** [comment]
Hello Jian,

You can of course set the title in the XML. 

If you want to set the text dynamically, currently there are not methods for that (I will add them soon, maybe in a couple of hours)

Until then you can change the title by using a little workaround:

java```

ExpandableCardView myCard = findViewById(R.id.mycard);
myCard.findViewById(R.id.title).setText("Title");

```

This code accesses the TextView inside the Expandable Card, so you can do whatever you want with it.
But i will add `setTitle()` and `setIcon()` ASAP ;)

**Comment by JianHaoZhangHB** [comment]
Thank you for answering my question, just by chance to see such a good project, after use, want to make it more perfect. Thank you for open source.

**Comment by AleSpero** [comment]
Thank you for your kind words! Using the cards in a Recyclerview it's a feature i want to add, so if you manage to make an adapter for this, please consider making a pull request, so i can merge your feature into the codebase :)
