### ISSUE TITLE
Add setter for ANIMATION_DURATION

### ISSUE THREAD

**Issue by j-ns** [AleSpero/ExpandableCardView#4]
It would be nice to have a setter for ANIMATION_DURATION, as well as the possibility to disable the animation completely, i.e. to expand / collapse the cardview immediately

**Comment by AleSpero** [comment]
Hello j-ns. 

I thought about it too, but i didn't think it would be requested by someone. 
Since it is now, i'm probably add it in a new release today or tomorrow.

Stay tuned :)

**Comment by AleSpero** [comment]
Forgot to say that the setter is added in version 0.7.

Cheers!
