### ISSUE TITLE
well

### ISSUE THREAD

**Issue by VaibhavNalawade** [AleSpero/ExpandableCardView#41]
ERROR: Manifest merger failed : uses-sdk:minSdkVersion 17 cannot be smaller than version 21 declared in library [com.alespero:expandable-cardview:0.8] C:\Users\vn149\.gradle\caches\transforms-2\files-2.1\77a8e153d09f09dd93369c863f2522a3\AndroidManifest.xml as the library might be using APIs not available in 17
	Suggestion: use a compatible library with a minSdk of at most 17,
		or increase this project's minSdk version to at least 21,
		or use tools:overrideLibrary="com.alespero.expandablecardview" to force usage (may lead to runtime failures)

**Comment by AleSpero** [comment]
Hello,

The minimum supported version for this library is API 21, so by setting a minSdkVersion 17 in your app, the compilation failed.

Currently, there are no plans of lowering the minSdk, but i will definitely get back to you if this happens.

Regards,

Alessandro
